artifact_location: /home/wmreese/my_repos/week-1-intro-to-deep-rl-and-agent-training-environments-wrlaxboy151/submission/mlflow/585813452748047346
creation_time: 1694733617583
experiment_id: '585813452748047346'
last_update_time: 1694733617583
lifecycle_stage: active
name: <my_experinemnt>
